spring:
  application:
    name: notification-server

  profiles:
    active: ${SPRING_PROFILE:local}

  jpa:
    open-in-view: false

server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  server:
    port: 9090